# azure-pipelines.yml
trigger:
- main  # Replace with your default branch name if it's different

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, Azure Pipelines!"
  displayName: 'Print greeting'
