trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

steps:
  - script: |
      echo "PHP version:"
      php -v
    displayName: 'Show PHP Version'
